import { Navbar } from '@/components/organisms';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Link from 'next/link';

import '../../globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function PagesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <div className="p-8">
        <h1 className="text-xl text-primary font-bold mb-4">Dungeon Element</h1>
      </div>
      <div className="grid grid-cols-12 gap-4 h-screen">
        <div className="col-span-2 p-2">
          <Navbar />
        </div>
        <div className="col-span-10 px-8 py-4">{children}</div>
      </div>
    </div>
  );
}
